# Generated by Django 5.2.3 on 2025-07-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_sleeprecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SleepRecord',
        ),
    ]
